import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AppBar from './components/AppBar';
import { Provider } from './components/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Amiibo shelf',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + 'h-full w-full'}>
        <Provider>
          <AppBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
